name: Build

on:
    pull_request:

jobs:
    format:
        runs-on: ubuntu-latest
        name: Build Application
        steps:
            - name: Checkout
            - uses: actions/checkout@v3

            - name: Setup
            - uses: oven-sh/setup-bun@v2

            - name: Install
            - run: bun install

            - name: Build
            - run: bun run build
