name: Build

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Build
        run: bun run build
