on:
  push:
    paths:
      - 'flake.nix'

jobs:
  nix-check:
    name: Check Nix Dev Shell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@v12
      - name: Magic Nix Cache
        uses: https://github.com/DeterminateSystems/magic-nix-cache-action@v7
      - name: Check
        run: nix flake check -L
